name: Checkout Flow
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, World!"
      - name: list folder
        run: ls -l
        
      
